name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Run test.ts
        run: |
          deno test \
            --allow-read=testdata --allow-write=testdata \
            --coverage=coverage \
            test.ts

      - name: Analyze coverage
        run: |
          deno coverage coverage --lcov > coverage.lcov

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Check fmt
        run: deno fmt --check
