name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Run test.ts
        run: |
          deno test \
            --allow-read=testdata --allow-write=testdata \
            --coverage=coverage \
            test.ts

      - name: Analyze coverage
        run: deno coverage coverage
